name: manual-readme-sync
on:
  workflow_dispatch:
jobs:
  build-it:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Sync up docker hub readme nexusbackup
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_USERNAME }}
          pass: ${{ secrets.DOCKER_PASSWORD }}
          slug: davideshay/nexusbackup
          readme: README.md
          description: Sonatype Nexus Backup utility
